"""Init migration

Revision ID: b782d21078c6
Revises: 
Create Date: 2025-09-19 16:24:41.067824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b782d21078c6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spimex_trading_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exchange_product_id', sa.String(length=50), nullable=False),
    sa.Column('exchange_product_name', sa.String(length=255), nullable=False),
    sa.Column('oil_id', sa.String(length=10), nullable=False),
    sa.Column('delivery_basis_id', sa.String(length=10), nullable=False),
    sa.Column('delivery_basis_name', sa.String(length=255), nullable=False),
    sa.Column('delivery_type_id', sa.String(length=10), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spimex_trading_results_date'), 'spimex_trading_results', ['date'], unique=False)
    op.create_index(op.f('ix_spimex_trading_results_delivery_basis_id'), 'spimex_trading_results', ['delivery_basis_id'], unique=False)
    op.create_index(op.f('ix_spimex_trading_results_delivery_type_id'), 'spimex_trading_results', ['delivery_type_id'], unique=False)
    op.create_index(op.f('ix_spimex_trading_results_exchange_product_id'), 'spimex_trading_results', ['exchange_product_id'], unique=False)
    op.create_index(op.f('ix_spimex_trading_results_oil_id'), 'spimex_trading_results', ['oil_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spimex_trading_results_oil_id'), table_name='spimex_trading_results')
    op.drop_index(op.f('ix_spimex_trading_results_exchange_product_id'), table_name='spimex_trading_results')
    op.drop_index(op.f('ix_spimex_trading_results_delivery_type_id'), table_name='spimex_trading_results')
    op.drop_index(op.f('ix_spimex_trading_results_delivery_basis_id'), table_name='spimex_trading_results')
    op.drop_index(op.f('ix_spimex_trading_results_date'), table_name='spimex_trading_results')
    op.drop_table('spimex_trading_results')
    # ### end Alembic commands ###
